Sikap/Sikap/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

Sikap/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('',views.LandingView.as_view(),name="landing_view"),
    path('login/',views.LoginView.as_view(),name="login_view"),
    path('register/a',views.RegisterViewA.as_view(),name="registera_view"),
    path('register/e',views.RegisterViewE.as_view(),name="registere_view"),
    path('view/a',views.ViewAsAView.as_view(),name="viewasa_view"),
    path('view/e',views.ViewAsEView.as_view(),name="viewase_view"),
    path('posts/',views.PostsView.as_view(),name="posts_view"),
    path('view/get/ajax/friend', views.LiveSearch , name="LiveSearch"),
]

Sikap/app/templates/Applicant_Registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <style>
    .navbar{    
        background: whitesmoke;
        opacity: 1;
    }
    .nav-right {
        float: right;
    }

    </style>
</head>
<body>
    <nav class="navbar sticky-top navbar-light bg-dark">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Sikap</a>
          </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li class="text-secondary"><a href="#">Find Employers</a></li>
                <li class="text-secondary"><a href="#">Profile</a></li>
                <li><a href="#" class="text-secondary">Explore</a></li>
            </ul>
            <div class="nav-right">
                <form class="form-inline my-2 my-lg-0 al" style="padding-top: 10px;">                        
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" style="background: #0496ff;" type="submit">Search</button>
                </form>   
            </div>
        </div>
    </nav>
    <div class="container">
        <form class="form-horizontal" action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label col-sm-2" for="aemail">Email address</label>
                <div class="col-md-8">
                <input type="text" name="aemail" placeholder="Email" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="apassword">Password</label>
                <div class="col-md-8">
                <input type="password" name="apassword" placeholder="Password" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="aname">First Name</label>
                <div class="col-md-8">
                <input type="text" name="aname" id="" placeholder="Name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="asurname">Last Name</label>
                <div class="col-md-8">
                <input type="text" name="asurname" id="" placeholder="Last Name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="aindustry">Industry</label>
                <div class="col-md-8">
                <input type="text" name="aindustry" placeholder="Industry" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="aregion">Region</label>
                <div class="col-md-8">
                <input type="text" name="aregion" placeholder="Region" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="aprovince">Province</label>
                <div class="col-md-8">
                <input type="text" name="aprovince" placeholder="Province" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="acity">City</label>
                <div class="col-md-8">
                <input type="text" name="acity" placeholder="City" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="aage">Age</label>
                <div class="col-md-8">
                <input type="number" name="aage" placeholder="Age" value="18" class=form-control>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8">
                <label class="control-label col-sm-2" for="aage"></label>    
                <button type="submit" name="applicant" class="btn btn-primary">Register</button><br><br>           
                </div>
            </div>
        </form>
    </div>

</body>
</html>

Sikap/app/templates/Employer_Registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <style>
    .navbar{    
        background: whitesmoke;
        opacity: 1;
    }
    .nav-right {
        float: right;
    }

    </style>
</head>
<body>
    <nav class="navbar sticky-top navbar-light bg-dark">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Sikap</a>
          </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li class="text-secondary"><a href="#">Find Employers</a></li>
                <li class="text-secondary"><a href="#">Profile</a></li>
                <li><a href="#" class="text-secondary">Explore</a></li>
            </ul>
            <div class="nav-right">
                <form class="form-inline my-2 my-lg-0 al" style="padding-top: 10px;">                        
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" style="background: #0496ff;" type="submit">Search</button>
                </form>   
            </div>
        </div>
    </nav>
    <div class="container">
        <form class="form-horizontal" action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label col-sm-2" for="eemail">Email address</label>
                <div class="col-md-8">
                <input type="text" name="eemail" placeholder="Email" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="epassword">Password</label>
                <div class="col-md-8">
                <input type="password" name="epassword" placeholder="Password" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="ename">First Name</label>
                <div class="col-md-8">
                <input type="text" name="ename" id="" placeholder="Name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="esurname">Last Name</label>
                <div class="col-md-8">
                <input type="text" name="esurname" id="" placeholder="Last Name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="ecompanyName">Company</label>
                <div class="col-md-8">
                <input type="text" name="ecompanyName" placeholder="Company Name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="eindustry">Industry</label>
                <div class="col-md-8">
                <input type="text" name="eindustry" placeholder="Industry" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8">
                <label class="control-label col-sm-2" for="aage"></label>    
                <button type="submit" name="employer" class="btn btn-primary">Register</button><br><br>           
                </div>
            </div>
        </form>
    </div>

</body>
</html>

Sikap/app/templates/applicant.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<style>
    body {
  background: #F1F3FA;
  height: 1000px;
}

/* Profile container */
.profile {
  margin: 20px 0;
}

#wrapper{
    position: fixed;
}
#panel{
    float: right;
    position:fixed;
}

#info{
    position: fixed;
}
nav{
    color: black;
}

.container{
    padding-top: 3%;
}

.navbar{
    width: 100%;
    position: fixed;
    background: whitesmoke;
    opacity: 1;
}
.nav-right {
    float: right;
}

.row-profile {
    margin-top: 20px;
}
/* Profile sidebar */
.profile-sidebar {
  margin: 20px;
  padding: 20px 0 10px 0;
  background: #fff;
}

.profile-userpic img {
  float: none;
  margin: 0 auto;
  width: 50%;
  height: 50%;
  -webkit-border-radius: 50% !important;
  -moz-border-radius: 50% !important;
  border-radius: 50% !important;
}

.profile-usertitle {
  text-align: center;
  margin-top: 20px;
}

.profile-usertitle-name {
  color: #5a7391;
  font-size: 16px;
  font-weight: 600;
  margin-bottom: 7px;
}

.profile-usertitle-job {
  text-transform: uppercase;
  color: #5b9bd1;
  font-size: 12px;
  font-weight: 600;
  margin-bottom: 15px;
}

.profile-userbuttons {
  text-align: center;
  margin-top: 10px;
}

.profile-userbuttons .btn {
  text-transform: uppercase;
  font-size: 11px;
  font-weight: 600;
  padding: 6px 15px;
  margin-right: 5px;
}

.profile-userbuttons .btn:last-child {
  margin-right: 0px;
}

.profile-usermenu {
  margin-top: 30px;
}

.profile-usermenu ul li {
  border-bottom: 1px solid #f0f4f7;
}

.profile-usermenu ul li:last-child {
  border-bottom: none;
}

.profile-usermenu ul li a {
  color: #93a3b5;
  font-size: 14px;
  font-weight: 400;
}

.profile-usermenu ul li a i {
  margin-right: 8px;
  font-size: 14px;
}

.profile-usermenu ul li a:hover {
  background-color: #fafcfd;
  color: #5b9bd1;
}

.profile-usermenu ul li.active {
  border-bottom: none;
}

.profile-usermenu ul li.active a {
  color: #5b9bd1;
  background-color: #f6f9fb;
  border-left: 2px solid #5b9bd1;
  margin-left: -2px;
}

/* Profile Content */
.profile-content {
  padding: 20px;
  margin-top: 3.8%;
  background: #fff;
  min-height: 450px;
  height: 600px;
}
.profile-content h1 {
  text-transform: uppercase;
  color: #5a7391;
  font-size: 20px;
  font-weight: 600;
}

.profile-content p {
  color: #5b9bd1;
  font-size: 16px;
  font-weight: 600;
}
</style>
<body>
{% load static %}
    <nav class="navbar sticky-top navbar-light bg-dark">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Sikap</a>
          </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li class="text-secondary"><a href="#">Find Employers</a></li>
                <li class="text-secondary"><a href="#">Profile</a></li>
                <li><a href="#" class="text-secondary">Explore</a></li>
            </ul>
            <div class="nav-right">
                <form class="form-inline my-2 my-lg-0 al" style="padding-top: 10px;">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" style="background: #0496ff;" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row profile">
            <div class="col-md-3" >
                <div class="profile-sidebar" id="wrapper">


                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">
                        <img src="{% static 'avatar.jpg'%}" class="img-responsive" alt="">
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->

                    <div class="profile-usertitle">

                        <div class="profile-usertitle-name">
                        {{request.session.name}}
                        </div>
                        <div class="profile-usertitle-job">
                        {{request.session.industry}}
                        </div>


                    </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR BUTTONS -->
                    <div class="profile-userbuttons">


                        <form action="" method="POST">
                          {% csrf_token %}
                          <input type="hidden" value="{{profile.email}}" name="email">
                          <button type="button" class="btn btn-success btn-sm">Find</button>
                          <button type="submit" class="btn btn-danger btn-sm" name="post">CREATE POST</button>
                          <button type="submit" class="btn btn-danger btn-sm" name="logout">Logout</button>

                        </form>
                    </div>
                    <!-- END SIDEBAR BUTTONS -->
                    <!-- SIDEBAR MENU -->
                    <div class="profile-usermenu">
                        <ul class="nav">
                            <li class="active">
                                <a href="#">
                                <i class="glyphicon glyphicon-home"></i>
                                Overview </a>
                            </li>
                            <li>
                                <a href="#">
                                <i class="glyphicon glyphicon-user"></i>
                                Account Settings </a>
                            </li>
                            <li>
                                <a href="#" target="_blank">
                                <i class="glyphicon glyphicon-ok"></i>
                                Tasks </a>
                            </li>
                            <li>
                                <a href="#">
                                <i class="glyphicon glyphicon-flag"></i>
                                Help </a>
                            </li>
                        </ul>
                    </div>
                    <!-- END MENU -->

                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-content">
                  <h1> NAME: {{request.session.name}} {{request.session.surname}} &nbsp&nbsp AGE: {{request.session.age}}</h1>
                  <br />
                  <p>INDUSTRY: {{request.session.industry}}  &nbsp&nbsp REGION: {{request.session.region}} </p>
                  <br />
                  <p>PROVINCE: {{request.session.province}}  &nbsp&nbsp CITY: {{request.session.city}} </p>
                </div>
            </div>
            <div class="col-md-3" id="info">
            </div>
        </div>
    </div>

</body>

</html>

Sikap/app/templates/blogin.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="305272894627-ded3h2oanff0qiaotv10om5gnfu2b7nc.apps.googleusercontent.com">
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <input type = "email" name = "email" tabindex = "1" class = "input-field" placeholder = "Enter Email"  required> 
        <input type = "password" name = "pass" tabindex = "2" class = "input-field" placeholder = "Enter Password"required>
        <input type = "submit" value = "LOGIN" tabindex = "3">
    </form>
    <div class="g-signin2" data-onsuccess="onSignIn"></div>
    <a href="#" onclick="signOut();">Sign out</a>
    <script>
        function onSignIn(googleUser) {
        var profile = googleUser.getBasicProfile();
        console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
        console.log('Name: ' + profile.getName());
        console.log('Image URL: ' + profile.getImageUrl());
        console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
        }
        function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
        console.log('User signed out.');
        });
        }
    </script>
</body>
</html>

Sikap/app/templates/createpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <title>Create Post</title>
    <!-- {% load static %} -->
    <link rel="stylesheet" href="{% static 'style.css'%}">
    <style>
        *{
    margin : 0;
    padding : 0;
    box-sizing : border-box;
    outline: none;
    color: whitesmoke;
    font-family: 'Roboto', sans-serif;
}

body{
    width: 100%;
    height: 100vh;
    color: #fff;
    background: linear-gradient(to left, #EE7752, #E73C7E, #23A6D5, #23D5AB);
    background-size: 400% 400%;
    position: relative;
    animation: change 20s ease-in-out infinite;
}

@keyframes change {
    0%{
        background-position: 0 50%;
    }
    50%{
        background-position: 100% 50%;
    } 
    100%{
        background-position: 0 50%;
    } 
}

.wrapper{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    width: 100%;
    padding: 0 20px;
}

.post-form{
    max-width: 550px;
    margin: 0 auto;
    background: rgba(0,0,0,0.8);
    padding: 30px;
    border-radius: 5px;
    display: flex;
    box-shadow: 0 0 10px rgba(0,0,0,0.13);
}

.input-fields{
    display: flex;
    flex-direction: column;
    margin-right: 4%;
}

.input-fields .input{
    margin: 10px 0;
    background: transparent;
    border: 0;
    border-bottom: 2px solid whitesmoke;
    padding: 10px;
    color: whitesmoke;
    width:100%;
}

.input-fields .checkbox{
    position: relative;
    width: 80px;
    height: 40px;
    -webkit-appearance: none;
    background: #c6c6c6;
    outline: none;
    border-radius: 20px;
    box-shadow: inset 0 0 5px rgba(0,0,0,.2);
    /*transition: .5s;*/
}

.input-fields .checkbox:checked{
    background: #03a9f4;
}

.input-fields .checkbox:before{
    content: '';
    position: absolute;
    width:40px;
    height:40px;
    border-radius: 20px;
    top:0;
    left:0;
    background: #fff;
    transform: scale(1,1);
    box-shadow: 0 2px 5px rgba(0,0,0,0.2);
    transition: .5s;
}

.input-fields .checkbox:checked:before{
    left: 40px;
}

.input-fields .submit{
    padding: 15px;
    float: right;
    background: #19B3D3;
    text-decoration: none;
    text-align: center;
    border-radius: 5px;
    font-size: 15px;
    font-weight: 600;
    color: #fff;
    transition: .5s;
    transition-property: background;
}

.input-fields .submit:hover{
    background: #fff;
    color: #0D9DBB;
}
    </style>
</head>
<body>
    <div class="wrapper">
        <div class ="post-form">
            <div class ="input-fields">
                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="hidden" value="{{profile.email}}" name="email">
                    <input type="number" class="input" name="yearsOfExperience" placeholder="Years of Experience">
                    <input type="text" class="input" name="position" placeholder="Position / Job Title">
                    <input type="text" class="input" name="industry" placeholder="Industry" value="{{request.session.industry}}">
                    <input type="text" class="input" name="region" placeholder="Region" value="{{request.session.region}}">
                    <input type="text" class="input" name="province" placeholder="Province" value="{{request.session.province}}">
                    <input type="text" class="input" name="city" placeholder="City" value="{{request.session.city}}">
                    <input type="number" class="input" name="age" placeholder="Age" value="{{request.session.age}}">
                    <br>
                    <br>
                    <input type="checkbox" class="checkbox" name="isAgeViewable">
                    <p>Display Age?</p>
                    <button type="submit" class="submit" name="posts">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Sikap/app/templates/landing.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LANDING</title>
</head>
<body>
    LANDING
    <button><a href="{{ url 'login_view' }}">LOGIN</a></button>
</body>
</html>

Sikap/app/templates/login.html
<html>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<style>
    body {
    margin: 0;
    padding: 0;
    background-color: #FFFFFF;
    height: 100vh;
    color: black;
}
    .form-control{
        background-color: #c9c9c9;
        color: #FFF;
    }
#login .container #login-row #login-column #login-box {
    max-width: 600px;
    height: 320px;
    border: 1px solid #9C9C9C;
    background-color: #0496ff;
}
#login .container #login-row #login-column #login-box #login-form {
    padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
    margin-top: -85px;
}
</style>

<body>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="POSt">
                            {% csrf_token %}
                            <h3 class="text-center">Login</h3>
                            <div class="form-group">
                                <label for="email" class="text-black">Email:</label><br>
                                <input type="text" name="email" id="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="pass" class="text-black">Password:</label><br>
                                <input type="password" name="pass" id="pass" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="remember-me" class="text-black"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                                <input type="submit" name="submit" class="btn btn-secondary" value="submit">
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="{% url 'app:landing_view' %}" class="text-white">Register here</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Sikap/app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
</head>
<body>
    
    <form action="" method="POST">
        {% csrf_token %}
        FOR APPLICANT
        <input type="text" name="aemail" placeholder="Email">
        <input type="password" name="apassword" placeholder="Password">
        <input type="text" name="aname" id="" placeholder="Name">
        <input type="text" name="asurname" id="" placeholder="Last Name">
        <input type="text" name="aindustry" placeholder="Industry">
        <input type="text" name="aregion" placeholder="Region">
        <input type="text" name="aprovince" placeholder="Province">
        <input type="text" name="acity" placeholder="City">
        <input type="number" name="aage" placeholder="Age" value="18">
        <button type="submit" name="applicant">Register</button><br><br>
        FOR EMPLOYER
        <input type="text" name="eemail" placeholder="Email">
        <input type="password" name="epassword" placeholder="Password">
        <input type="text" name="ename" id="" placeholder="Name">
        <input type="text" name="esurname" id="" placeholder="Last Name">
        <input type="text" name="ecompanyName" placeholder="Company Name">
        <input type="text" name="eindustry" placeholder="Industry">
        <button type="submit" name="employer">Register</button><br>
    </form>
</body>
</html>

Sikap/app/templates/viewas.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ViewAs</title>
</head>
<body>
    VIEW AS
</body>
</html>